# Generated by Django 3.1.7 on 2021-03-24 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('nickname', models.CharField(max_length=25)),
                ('birth_date', models.DateField(default='0000-00-00')),
                ('profile_image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DailyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_time', models.TimeField()),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_image', models.CharField(max_length=200)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField()),
                ('text', models.CharField(max_length=1500)),
                ('is_private', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserBaby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.baby')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dailybabyapi.relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.dailyuser')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.entry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailybabyapi.prompt'),
        ),
        migrations.AddField(
            model_name='entry',
            name='user_baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.userbaby'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('content', models.CharField(max_length=500)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.dailyuser')),
            ],
        ),
    ]
