# Generated by Django 3.1.7 on 2021-03-18 16:15

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('nickname', models.CharField(max_length=25)),
                ('birth_date', models.DateField(default='0000-00-00')),
                ('profile_image', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/fluffydaydream/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,b_rgb:262c35/v1615834269/blank-profile-picture-973460_640_rtmmdv.png', max_length=255, verbose_name='profile_image')),
            ],
        ),
        migrations.CreateModel(
            name='DailyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_time', models.TimeField(null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_image', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/fluffydaydream/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,b_rgb:262c35/v1615834269/blank-profile-picture-973460_640_rtmmdv.png', max_length=255, verbose_name='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField()),
                ('text', models.CharField(max_length=1500)),
                ('is_private', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserBaby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.baby')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dailybabyapi.relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.dailyuser')),
            ],
        ),
        migrations.CreateModel(
            name='StagePrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.prompt')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.entry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailybabyapi.prompt'),
        ),
        migrations.AddField(
            model_name='entry',
            name='user_baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.userbaby'),
        ),
        migrations.CreateModel(
            name='DailyUserDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.dayofweek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.dailyuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('content', models.CharField(max_length=200)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.entry')),
                ('user_baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.userbaby')),
            ],
        ),
    ]
