# Generated by Django 3.1.7 on 2021-05-12 01:58

import dailybabyapi.models.daily_user
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailybabyapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyuser',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='dailyuser',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='dailyuser',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='dailyuser',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='dailyuser',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='dailyuser',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='dailyuser',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='dailyuser',
            name='days_of_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=dailybabyapi.models.daily_user.DailyUser.days_default, size=7),
        ),
    ]
