# Generated by Django 3.1.7 on 2021-04-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailybabyapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.CharField(max_length=140)),
                ('phone_number', models.CharField(max_length=15)),
                ('execution_time', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailybabyapi.dailyuser')),
            ],
        ),
    ]
