# Generated by Django 3.1.7 on 2021-03-15 18:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailybabyapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/fluffydaydream/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,b_rgb:262c35/v1615834269/blank-profile-picture-973460_640_rtmmdv.png', max_length=255, verbose_name='profile_image'),
        ),
        migrations.AlterField(
            model_name='dailyuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/fluffydaydream/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,b_rgb:262c35/v1615834269/blank-profile-picture-973460_640_rtmmdv.png', max_length=255, verbose_name='profile_image'),
        ),
        migrations.AlterField(
            model_name='dailyuser',
            name='text_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_on',
            field=models.DateField(),
        ),
    ]
